### ISSUE TITLE
Ocean Control MUX not working?

### ISSUE THREAD

**Issue by awmayhall** [coryjfowler/MAX31855_lib#5]
Hey, so I've been playing around with an Ocean control KTA-259K shield and I have been trying to get this library to work but for some reason, I just can't seem to read the values of any thermocouple attached to it using the provided examples. 

I'm using a genuine Arduino MEGA 2560 Rev 3 and the shield with a single k type thermocouple attached to TC1. Both the serial test and Mux test will not read the values of the thermocouple attached to any channel. Nor will it display errors if I hook up the thermocouple backward purposely as I see in the code there are serial messages for those cases.   

In the MUX test, I see it run through the channels printing 0C and cold junction temperature of 32C. 
In the Serial test, it is the same thing with the readings happening around 68us. Doesn't matter if I change the channel or hook the probe up with reversed polarity. 

However, when using the sample sketch provided by Ocean Control, I am able to read thermocouple values on all channels as well as errors so I know the hardware works and is at the very least compatible with the MEGA. This leads me to believe that something is wrong with this library or it doesn't work with the specific hardware?  I know the readme mentioned an UNO so could it be that simple? Or is there something I am missing in the provided examples?

Any help would be greatly appreciated. I know this library hasn't been updated in a while and I really don't know what I am doing so I could be goofing up!

Thanks.

**Comment by nikolarobottesla** [comment]
@awmayhall Did you set the MUX #define in the header file (MAX31855.h)?  Did you change any of the pins in the sample sketch from Ocean Control? If you did update those pins in the header file as well.
![image](https://user-images.githubusercontent.com/13294739/118991977-d3143480-b949-11eb-80ae-4d84cf3b5c95.png)

**Comment by awmayhall** [comment]
@nikolarobottesla, Thanks for following up! I did try that and I did mess around with the pins assignment etc. Unfortunately, I just wasn't able to get the library to work. I reached out to Ocean Controls and they informed me they did a hardware revision (Looks like the library worked with v3, they are now on v5) and that it likely broke some of the libraries. They provided me with an example sketch that was better than their published one and worked for my needs at the time. I will circle back sometime soon and give it another poke or two and see if I can make it work using this library.  Thanks again!

**Comment by coryjfowler** [comment]
I am willing to bet the example they supplied is bit-banging SPI over the GPIO pins.  The Arduino Mega has the SPI pins on the ICSP header only.  I am a bit disappointed to hear they've made revisions, but skipped bringing their shield up the "R3" specs... I'd have bought another one so I can use it with other non-UNO boards!

I made this library because the bit-banging process they use in their example is SLOW.  I'd suggest you rewire your board to take advantage of the SPI peripheral in the ATmega.

**Comment by nikolarobottesla** [comment]
Yes they are bit-banging SPI in the Ocean Controls example from their website. The MuxTest example works for me on an Arduino UNO probably because the UNO's SPI bus is in the correct spot for the Ocean Controls board.  I've also got an Arduino 101 which supposedly has the SPI bus in the same place as the UNO but doesn't work with the MuxTest example. I'm guessing it's a timing issue, intel :(
